In [1]:
import numpy as np
from numpy.random import randn

In [2]:
np.set_printoptions(precision=2)

# Creating Arrays w/ Lists

In [3]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [6]:
b = np.array([[10,20,20],[40,50,60]])
b

array([[10, 20, 20],
       [40, 50, 60]])

# Creating Arrays w/ Assignment

In [5]:
np.random.seed(25)
c = 36*np.random.randn(6)
c

array([  8.22,  36.97, -30.23, -21.28, -34.45,  -8.  ])

In [8]:
d = np.arange(1,35)
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

# Performing Operations

In [9]:
a*10

array([10, 20, 30, 40, 50, 60])

In [10]:
c + a

array([  9.22,  38.97, -27.23, -17.28, -29.45,  -2.  ])

# Multiplying Matrices / Lin Alg

In [14]:
aa = np.array([[1.,2.,3.],[4.,5.,6.],[2.,5.,6.]])
aa

array([[1., 2., 3.],
       [4., 5., 6.],
       [2., 5., 6.]])

In [13]:
bb = np.array([[5.,3.,0.],[1.,5.,6.],[3.,5.,6.]])
bb

array([[5., 3., 0.],
       [1., 5., 6.],
       [3., 5., 6.]])

In [15]:
aa*bb

array([[ 5.,  6.,  0.],
       [ 4., 25., 36.],
       [ 6., 25., 36.]])

In [16]:
np.dot(aa,bb)

array([[16., 28., 30.],
       [43., 67., 66.],
       [33., 61., 66.]])