In [1]:
import numpy as np
import pandas as pd
import sklearn

from pandas import Series, DataFrame
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

In [2]:
from sklearn.linear_model import Perceptron

In [6]:
iris = datasets.load_iris()

x = iris.data
y = iris.target

x[0:10,]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [7]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [8]:
standardize = StandardScaler()

standardized_x_test = standardize.fit_transform(x_test)
standardized_x_train = standardize.fit_transform(x_train)

In [9]:
standardized_x_test[0:10,]

array([[-0.42950726, -0.00776408,  0.45915479,  0.39699293],
       [-0.08125813, -0.70653111,  0.0765258 , -0.00902257],
       [-0.77775639,  0.9239253 , -1.45399017, -1.09173056],
       [ 1.48586295, -0.00776408,  0.90555528,  1.47970092],
       [ 0.78936469, -1.63822048,  0.39538329,  0.12631593],
       [ 0.61524013, -1.87114283,  0.45915479,  0.39699293],
       [ 0.44111556, -0.00776408,  0.71424078,  0.80300843],
       [-1.82250378,  0.9239253 , -1.19890417, -1.36240756],
       [-0.25538269, -0.00776408,  0.26784029, -0.00902257],
       [-1.64837921,  0.22515827, -1.45399017, -1.49774605]])

In [10]:
perceptron = Perceptron(max_iter=50, eta0=0.15, tol=1e-3, random_state=15)

perceptron.fit(standardized_x_train, y_train.ravel())

Perceptron(eta0=0.15, max_iter=50, random_state=15)

In [11]:
ypred = perceptron.predict(standardized_x_test)

In [12]:
print(y_test)

[1 1 0 2 1 1 2 0 1 0 0 0 2 1 0 2 2 2 1 2 1 2 1 0 1 1 2 0 2 0]


In [13]:
print(ypred)

[1 1 0 2 1 1 1 0 1 0 0 0 2 1 0 1 2 1 1 1 1 2 1 0 1 1 1 0 2 0]


In [14]:
print(classification_report(y_test, ypred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       0.69      1.00      0.81        11
           2       1.00      0.50      0.67        10

    accuracy                           0.83        30
   macro avg       0.90      0.83      0.83        30
weighted avg       0.89      0.83      0.82        30

